#!/bin/bash
set +x

# Ensure Homebrew is installed & updated
echo -n 'Installing/Updating Homebrew... '
  which -s brew
  if [[ $? != 0 ]] ; then
    /usr/bin/ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
  else
    brew update 2>&1 > /dev/null
  fi
echo 'Done!'

# ElasticSearch
which -s elasticsearch || (
  echo -n 'Installing ElasticSearch... '
  brew install elasticsearch 2>&1 > /dev/null
  mkdir -p ~/Library/LaunchAgents 2>&1 > /dev/null
  launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist 2>&1 > /dev/null
  ln -nfs /usr/local/Cellar/elasticsearch/0.19.9/homebrew.mxcl.elasticsearch.plist ~/Library/LaunchAgents/ 2>&1 > /dev/null
  launchctl load -wF ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist 2>&1 > /dev/null
  echo 'Done!'
)

# Redis
which -s redis-cli || (
  echo -n 'Installing Redis... '
  brew install redis 2>&1 > /dev/null
  mkdir -p ~/Library/LaunchAgents 2>&1 > /dev/null
  launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.redis.plist 2>&1 > /dev/null
  cp /usr/local/Cellar/redis/2.4.17/homebrew.mxcl.redis.plist ~/Library/LaunchAgents/ 2>&1 > /dev/null
  launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.redis.plist 2>&1 > /dev/null
  echo 'Done!'
)

# MongoDB
which -s mongo || (
  echo -n 'Installing MongoDB... '
  brew install mongodb 2>&1 > /dev/null
  mkdir -p ~/Library/LaunchAgents 2>&1 > /dev/null
  launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist 2>&1 > /dev/null
  launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist 2>&1 > /dev/null
  echo 'Done!'
)

# icu4c
which -s || (
  echo -n 'Installing icu4c... '
  brew install icu4c 2>&1 > /dev/null
  echo 'Done!'
)

# Config
if [ ! -f config/application.yml ];
then
  echo -n 'Copying config file... '
    cp config/application.example.yml config/application.yml 2>&1 > /dev/null
  echo 'Done!'
fi

# Foreman
echo -n 'Setting up foreman... '
  echo 'RACK_ENV=development' >> .env
  echo 'PORT=5000' >> .env
echo 'Done!'

# Bundler
echo -n 'Bundling... '
  bundle config build.charlock_holmes --with-icu-dir=/usr/local/opt/icu4c
  bundle install --quiet
echo 'Done!'
